// 2級のカラーデータ
export default [
  { id: 1, name: '鴇色', yomi: 'ときいろ', explain: '明るい紫みの赤', code: '#f4b3c2', category: 'R' },
  { id: 2, name: '韓紅色', yomi: 'からくれないいろ', explain: 'あざやかな赤', code: '#e95464', category: 'R' },
  { id: 3, name: '蘇芳', yomi: 'すおう', explain: 'くすんだ赤', code: '#9e3d3e', category: 'R' },
  { id: 4, name: '鳶色', yomi: 'とびいろ', explain: '暗い黄みの赤', code: '#8b4239', category: 'R' },
  { id: 5, name: '弁柄色', yomi: 'べんがらいろ', explain: '暗い黄みの赤', code: '#8f2d12', category: 'R' },
  { id: 6, name: '海老茶', yomi: 'えびちゃ', explain: '暗い黄みの赤', code: '#814336', category: 'R' },
  { id: 7, name: 'ローズピンク', yomi: '', explain: '明るい紫みの赤', code: '#eb96a0', category: 'R' },
  { id: 8, name: 'バーガンディ', yomi: '', explain: 'ごく暗い紫みの赤', code: '#432a31', category: 'R' },
  { id: 9, name: 'オールドローズ', yomi: '', explain: 'やわらかい赤', code: '#da8d93', category: 'R' },
  { id: 10, name: 'ポピーレッド', yomi: '', explain: 'あざやかな赤', code: '#e9474d', category: 'R' },
  { id: 11, name: 'マルーン', yomi: '', explain: '暗い赤. マルーン(Maroon)とはスペイン産の大粒の西洋栗のことです。', code: '#6a1816', category: 'R' },
  { id: 12, name: 'テラコッタ', yomi: '', explain: 'くすんだ黄みの赤. テラコッタ(Terracotta)とはイタリア語で「焼いた(cotta)土(terra)」という意味です。', code: '#be6d55', category: 'R' },
  { id: 13, name: '黄丹', yomi: 'おうに', explain: 'つよい黄赤', code: '#ee7948', category: 'YR' },
  { id: 14, name: '桧皮色', yomi: 'ひわだいろ', explain: '暗い灰みの黄赤', code: '#965036', category: 'YR' },
  { id: 15, name: '代赭', yomi: 'たいしゃ', explain: 'くすんだ黄赤', code: '#bb541f', category: 'YR' },
  { id: 16, name: '柑子色', yomi: 'こうじいろ', explain: '明るい黄赤', code: '#f6ad48', category: 'YR' },
  { id: 17, name: 'チャイニーズレッド', yomi: '', explain: 'あざやかな黄赤', code: '#ea5520', category: 'YR' },
  { id: 18, name: 'バーントシェンナ', yomi: '', explain: 'くすんだ黄赤', code: '#b25532', category: 'YR' },
  { id: 19, name: 'ローシェンナ', yomi: '', explain: 'つよい黄赤', code: '#d98032', category: 'YR' },
  { id: 20, name: 'タン', yomi: '', explain: 'くすんだ黄赤. タンとは草木に含まれるタンニンを使ってなめした牛皮のことです。', code: '#c1813f', category: 'YR' },
  { id: 21, name: '琥珀色', yomi: 'こはくいろ', explain: 'くすんだ赤みの黄', code: '#bf7834', category: 'Y' },
  { id: 22, name: '朽葉色', yomi: 'くちばいろ', explain: '灰みの赤みを帯びた黄', code: '#917347', category: 'Y' },
  { id: 23, name: '鬱金色', yomi: 'うこんいろ', explain: 'つよい黄', code: '#fabf13', category: 'Y' },
  { id: 24, name: '刈安色', yomi: 'かりやすいろ', explain: 'うすい緑みの黄', code: '#f5e56b', category: 'Y' },
  { id: 25, name: 'エクルベイジュ', yomi: '', explain: 'うすい赤みの黄', code: '#f8eacf', category: 'Y' },
  { id: 26, name: 'ゴールデンイエロー', yomi: '', explain: 'つよい赤みの黄', code: '#f8b856', category: 'Y' },
  { id: 27, name: 'アンバー', yomi: '', explain: 'くすんだ赤みの黄', code: '#c28953', category: 'Y' },
  { id: 28, name: 'バーントアンバー', yomi: '', explain: 'ごく暗い赤みの黄', code: '#7a5e3d', category: 'Y' },
  { id: 29, name: 'ローアンバー', yomi: '', explain: '暗い黄', code: '#916f24', category: 'Y' },
  { id: 30, name: 'ネープルスイエロー', yomi: '', explain: 'つよい黄', code: '#fdd75c', category: 'Y' },
  { id: 31, name: 'ジョンブリアン', yomi: '', explain: 'あざやかな黄', code: '#ffdc00', category: 'Y' },
  { id: 32, name: '黄蘗色', yomi: 'きはだいろ', explain: 'あかるい黄緑', code: '#fef263', category: 'GY' },
  { id: 33, name: '海松色', yomi: 'みるいろ', explain: '暗い灰みの黄緑', code: '#726d3f', category: 'GY' },
  { id: 34, name: '鶸色', yomi: 'ひわいろ', explain: 'つよい黄緑', code: '#d7cf3a', category: 'GY' },
  { id: 35, name: 'シャルトルーズグリーン', yomi: '', explain: '明るい黄緑', code: '#d9e367', category: 'GY' },
  { id: 36, name: 'リーフグリーン', yomi: '', explain: 'つよい黄緑', code: '#9dc04c', category: 'GY' },
  { id: 37, name: 'グラスグリーン', yomi: '', explain: 'くすんだ黄緑', code: '#7b8d41', category: 'GY' },
  { id: 38, name: '常磐色', yomi: 'ときわいろ', explain: 'こい緑', code: '#007c45', category: 'G' },
  { id: 39, name: '緑青色', yomi: 'ろくしょういろ', explain: 'くすんだ緑', code: '#4f8a5d', category: 'G' },
  { id: 40, name: 'アップルグリーン', yomi: '', explain: 'やわらかい黄みの緑', code: '#a2cc89', category: 'G' },
  { id: 41, name: 'ミントグリーン', yomi: '', explain: '明るい緑', code: '#98ce97', category: 'G' },
  { id: 42, name: 'マラカイトグリーン', yomi: '', explain: 'こい緑', code: '#009854', category: 'G' },
  { id: 43, name: 'ボトルグリーン', yomi: '', explain: 'ごく暗い緑', code: '#005635', category: 'G' },
  { id: 44, name: '鉄色', yomi: 'てついろ', explain: 'ごく暗い青緑', code: '#005242', category: 'G' },
  { id: 45, name: 'ピーコックグリーン', yomi: '', explain: '青緑', code: '#00a496', category: 'G' },
  { id: 46, name: 'ナイルブルー', yomi: '', explain: 'くすんだ青緑', code: '#259f94', category: 'B' },
  { id: 47, name: '新橋色', yomi: 'しんばしいろ', explain: '明るい緑みの青', code: '#64bcc7', category: 'B' },
  { id: 48, name: '納戸色', yomi: 'なんどいろ', explain: 'つよい緑みの青', code: '#007d92', category: 'B' },
  { id: 49, name: '甕覗', yomi: 'かめのぞき', explain: 'やわらかい緑みの青', code: '#a2d7dd', category: 'B' },
  { id: 50, name: '縹色', yomi: 'はなだいろ', explain: 'つよい青', code: '#2980af', category: 'B' },
  { id: 51, name: 'セルリアンブルー', yomi: '', explain: 'あざやかな青', code: '#008db7', category: 'B' },
  { id: 52, name: 'ミッドナイトブルー', yomi: '', explain: 'ごく暗い紫みの青', code: '#001d42', category: 'B' },
  { id: 53, name: '藤色', yomi: 'ふじいろ', explain: '明るい青紫', code: '#bbb7da', category: 'P' },
  { id: 54, name: 'ウィスタリア', yomi: '', explain: 'あざやかな青紫', code: '#8e8bc2', category: 'P' },
  { id: 55, name: '江戸紫', yomi: 'えどむらさき', explain: 'こい青みの紫', code: '#734e95', category: 'P' },
  { id: 56, name: '古代紫', yomi: 'こだいむらさき', explain: 'くすんだ紫', code: '#895687', category: 'P' },
  { id: 57, name: 'ライラック', yomi: '', explain: 'やわらかい紫', code: '#d3e9f9', category: 'P' },
  { id: 58, name: '銀鼠', yomi: 'ぎんねず', explain: '明るい灰色', code: '#afafb0', category: 'N' },
  { id: 59, name: '茶鼠', yomi: 'ちゃねず', explain: '黄赤みの灰色', code: '#a99e93', category: 'N' },
  { id: 60, name: '利休鼠', yomi: 'りきゅうねず', explain: '緑みの灰色', code: '#7b8174', category: 'N' },
  { id: 61, name: '煤竹色', yomi: 'すすたけいろ', explain: '赤みを帯びた黄みの暗い灰色', code: '#6b5146', category: 'N' },
  { id: 62, name: 'スレートグレイ', yomi: '', explain: '暗い灰色', code: '#636062', category: 'N' },
  { id: 63, name: 'ランプブラック', yomi: '', explain: '黒', code: '#24130d', category: 'N' },
]